package pt.isec.common.model.user;
import java.io.Serial;
import java.io.Serializable;
import java.time.LocalDateTime;

/**
 * Teacher entity.
 * <p>
 * Identified by an id generated by the database and sharing the common
 * fields defined in {@link User}.
 */
public final class Teacher extends User implements Serializable {
    @Serial
    private static final long serialVersionUID = 1L;

    /* ====================== CONSTRUCTORS ====================== */

    /**
     * Default constructor.
     * <p>
     * Initializes {@code createdAt} with the current timestamp.
     */
    public Teacher() {
        super();
    }

    /**
     * Constructs a teacher with basic fields.
     *
     * @param name         teacher name
     * @param email        email address
     * @param passwordHash hashed password
     * @throws IllegalArgumentException if any argument is invalid
     */
    public Teacher(String name, String email, String passwordHash) {
        super(name, email, passwordHash);
    }

    /**
     * Constructs a teacher with all fields.
     *
     * @param id           teacher id
     * @param name         teacher name
     * @param email        email address
     * @param passwordHash hashed password
     * @param createdAt    creation time (may be {@code null})
     * @throws IllegalArgumentException if any argument is invalid
     */
    public Teacher(long id, String name, String email, String passwordHash, LocalDateTime createdAt) {
        super(id, name, email, passwordHash, createdAt);
    }

    /* ======================== USER TYPE ======================= */

    /**
     * {@inheritDoc}
     */
    @Override
    public String getUserType() {
        return "teacher";
    }

    /* ======================= OBJECT METHODS ==================== */

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (!(o instanceof Teacher)) return false;
        // Delegate to User.equals for field comparison
        return super.equals(o);
    }

    @Override
    public int hashCode() {
        return super.hashCode();
    }

    @Override
    public String toString() {
        return "Teacher{" +
                "id=" + id +
                ", name='" + name + '\'' +
                ", email='" + email + '\'' +
                ", createdAt=" + createdAt +
                '}';
    }
}
